config/routes.rb
Digitalbattlemat::Application.routes.draw do
  mount MochaRails::Engine => 'mocha' unless Rails.env.production?
  resources :characters

  resources :mats

  

  resources :mats
end

app/models/anima_character.rb
class AnimaCharacter < Character
  include Mongoid::Document


  DEFAULT_CHARACTERISTICS = {
      :agility => 0,
      :strength => 0,
      :dexterity => 0,
      :constitution => 0,
      :intelligence => 0,
      :power => 0,
      :willpower => 0,
      :perception => 0
    }


  field :className,                 type: String
  field :characteristics,           type: Hash, default: DEFAULT_CHARACTERISTICS
  field :currentLifePoints,         type: Integer
  field :currentDevelopmentPoints,  type: Integer, default: 0
  field :lifePointsBought,          type: Integer, default: 0


  validates_each :characteristics do |record, attr, value|
    unless value.keys == DEFAULT_CHARACTERISTICS.keys then
      record.errors.add(
          :attr,
          'Does not contain the correct characteristics')
    end
  end
end

app/models/battle_mat.rb
class BattleMat < ActiveRecord::Base
  has_many :battle_mat_tiles

  validates_numericality_of :width, :greater_than_or_equal_to => 0
  validates_numericality_of :height, :greater_than_or_equal_to => 0
  
  def before_destroy
    self.battle_mat_tiles.delete_all
  end
end

app/models/battle_mat_tile.rb
class BattleMatTile < ActiveRecord::Base
  belongs_to :battle_mat, :validate => true

  validates_numericality_of :x_position, :greater_than_or_equal_to => 0
  validates_numericality_of :y_position, :greater_than_or_equal_to => 0
  validates_inclusion_of :visibility, :in => %w(visible hidden)
end

app/models/character.rb
class Character
  include Mongoid::Document

  field :name,        type: String
  field :description, type: String

  validates_presence_of :name

  TYPES = {
    :AnimaCharacter => AnimaCharacter
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    respond_to do |format|
      format.knockout_template do
        render partial: "#{@character._type.underscore}.html"
      end
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  def new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    type = params[:character].delete :type
    @character = Character::TYPES[type.to_sym].new(character_params)

    respond_to do |format|
      if @character && @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json
      else
        format.html { render action: 'new' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if true
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :description)
    end
end

app/controllers/mats_controller.rb
class MatsController < ApplicationController
  before_action :set_mat, only: [:show, :edit, :update, :destroy]

  # GET /mats
  # GET /mats.json
  def index
    @mats = Mat.all
  end

  # GET /mats/1
  # GET /mats/1.json
  def show
  end

  # GET /mats/new
  def new
    redirect_to :action => :index
  end

  # GET /mats/1/edit
  def edit
  end

  # POST /mats
  # POST /mats.json
  def create
    @mat = Mat.new(mat_params)

    respond_to do |format|
      if @mat.save
        format.html { redirect_to @mat }
        format.json { render action: 'show', status: :created, location: @mat }
      else
        format.html { render action: 'new' }
        format.json { render json: @mat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mats/1
  # PATCH/PUT /mats/1.json
  def update
    respond_to do |format|
      if @mat.update(mat_params)
        format.html { redirect_to @mat, notice: 'Mat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mats/1
  # DELETE /mats/1.json
  def destroy
    @mat.destroy
    respond_to do |format|
      format.html { redirect_to mats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mat
      @mat = Mat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mat_params
      params.require(:mat).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/mats_helper.rb
module MatsHelper
end

app/views/characters/_anima_character.html.erb
<div class="toolbarheader">
  <h1 data-bind="text: name"></h1>
  <div class=".ui-toolbar">
    <button id="action-character-editable-toggle"></button>
  </div>
</div>
<p>
  <strong><span data-bind="text: className"></span></strong>, 
  Level <strong><span data-bind="text: level"></span>
  <input type="number" min="1" max="20" data-bind="value: level" /></strong>—
  <span 
      class="character-details-description" 
      data-bind="htmlValue: description" contenteditable="false">
  </span>
</p>

<div class="multicol">
  <h2>Characteristics</h2>

  <table>
    <thead>
      <th></th>
      <th>Current</th>
      <th>Bonus</th>
    </thead>
    <tbody>
      <tr>
        <th>Agility</th>
        <td>
          <span data-bind="text: characteristics.agility"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[agility]"
              data-bind="value: characteristics.agility" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.agility())"></td>
      </tr>
      <tr>
        <th>Constitution</th>
        <td>
          <span data-bind="text: characteristics.constitution"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[constitution]"
              data-bind="value: characteristics.constitution" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.constitution())"></td>
      </tr>
      <tr>
        <th>Dexterity</th>
        <td>
          <span data-bind="text: characteristics.dexterity"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[dexterity]"
              data-bind="value: characteristics.dexterity" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.dexterity())"></td>
      </tr>
      <tr>
        <th>Strength</th>
        <td>
          <span data-bind="text: characteristics.strength"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[strength]"
              data-bind="value: characteristics.strength" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.strength())"></td>
      </tr>
      <tr>
        <th>Intelligence</th>
        <td>
          <span data-bind="text: characteristics.intelligence"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[intelligence]"
              data-bind="value: characteristics.intelligence" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.intelligence())"></td>
      </tr>
      <tr>
        <th>Perception</th>
        <td>
          <span data-bind="text: characteristics.perception"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[perception]"
              data-bind="value: characteristics.perception" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.perception())"></td>
      </tr>
      <tr>
        <th>Power</th>
        <td>
          <span data-bind="text: characteristics.power"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[power]"
              data-bind="value: characteristics.power" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.power())"></td>
      </tr>
      <tr>
        <th>Willpower</th>
        <td>
          <span data-bind="text: characteristics.willpower"></span>
          <input
              type="number"
              min="0" max="21"
              name="characteristics[power]"
              data-bind="value: characteristics.willpower" />
        </td>
        <td data-bind="text: character.characteristicsModifier(characteristics.willpower())"></td>
      </tr>
    </tbody>
  </table>

  <h2>Life Points</h2>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind="text: baseLifePoints"></td>
    </tr>
    <tr>
      <th>Class Bonus</th>
      <td data-bind="text: classBonusLifePoints"></td>
    </tr>
    <tr>
      <th>Multiples</th>
      <td data-bind="text: lifePointsBought"></td>
    </tr>
    <tr>
      <th>Total Full</th>
      <td data-bind="text: fullLifePoints"></td>
    </tr>
    <tr>
      <th>Current</th>
      <td>
        <span data-bind="text: currentLifePoints"></span>
        <input
            type="number"
            name="currentLifePoints"
            data-bind="value: currentLifePoints" />
      </td>
    </tr>
  </table>

  <h2>Movement</h2>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Penality</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Bonus</th>
      <td></td>
    </tr>
    <tr>
      <th>Total</th>
      <td data-bind=""></td>
    </tr>
  </table>

  <h2>Fatige</h2>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind="text: baseFatigue"></td>
    </tr>
    <tr>
      <th>Bonus</th>
      <td data-bind="text: bonusFatigue"></td>
    </tr>
    <tr>
      <th>Total Full</th>
      <td data-bind="text: fullFatigue"></td>
    </tr>
    <tr>
      <th>Current</th>
      <td>
        <span data-bind="htmlValue: currentFatigue"></span>
        <input 
          type="number"
          name="currentFatigue"
          min="0"
          data-bind="value: currentFatigue" />
      </td>
    </tr>
  </table>
</div>

<h2>Combat</h2>

<div class="multicol">
  
  <h3>Initiative</h3>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Dexterity</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Class Bonus</th>
      <td></td>
    </tr>
    <tr>
      <th>Total</th>
      <td data-bind=""></td>
    </tr>
  </table>

  <h3>Attack</h3>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Dexterity</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Class Bonus</th>
      <td></td>
    </tr>
    <tr>
      <th>Total</th>
      <td data-bind=""></td>
    </tr>
  </table>

  <h3>Block</h3>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Dexterity</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Class Bonus</th>
      <td></td>
    </tr>
    <tr>
      <th>Total</th>
      <td data-bind=""></td>
    </tr>
  </table>

  <h3>Dodge</h3>

  <table>
    <tr>
      <th>Base</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Agility</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Special</th>
      <td data-bind=""></td>
    </tr>
    <tr>
      <th>Class Bonus</th>
      <td></td>
    </tr>
    <tr>
      <th>Total</th>
      <td data-bind=""></td>
    </tr>
  </table>
</div>

<h2>Armor</h2>

<div class="toolbarheader">
  <h3>Armor Worn</h3>
  <div class=".ui-toolbar">
    <button id="action-character-add-armor"></button>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Location</th>
      <th>Cut</th>
      <th>Impact</th>
      <th>Thrust</th>
      <th>Heat</th>
      <th>Electricity</th>
      <th>Cold</th>
      <th>Energy</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<h3>Wear Armor</h3>

<h2>Secondary Abilities</h2>

<div class="multicol">

</div>


<h2>Inventory</h2>

<ul id="character-inventory" data-bind="foreach: inventory">
  <li class="editable" data-bind="click: $parent.toggleInventoryItemEditable">
    <button style="display: none" data-bind="click: $parent.removeInventoryItem"></button> 
    <span data-bind="text: $data" contenteditable="false"></span>
  </li>
</ul>

<input 
    type="text"
    placeholder="Add item to inventory..."
    id="character-action-inventory-add"
    style="display: none" />

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :characteristics %><br>
    <%= f.text_field :characteristics %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<div id="characters-list" class="content-box">
  <div>
    <h1>All Characters</h1>
    <div id="characters-list-actions">
      <button class="action-add-character"></button>
    </div>
  </div>

  <div id="new-character-dialog" title="Create a new Character">
    <form name="character">
      <fieldset>
        <label for="character[name]">Name</label>
        <input type="text" name="character[name]" placeholder="Character Name" />

        <label for "character[type]">Rule System</label>
        <select name="character[type]" class="ui-widget">
          <option value="AnimaCharacter">Anima</option>
        </select>
      </fieldset>
    </form>
  </div>

  <input type="search" placeholder="Search for Character..." id="search-character" />

  <div id="characters-list-items"></div>
</div>


<div id="characters-view" class="content-box">
  <div style="text-align:center" id="character-placeholder" data-bind="ifnot: currentCharacter">
    <h1 style="display: block;">Character Details</h1>
    <%= image_tag "Icon-Characters.png" %>
    <p>Select a character on the left site to display details,<br/>
      or click the <em>Add</em> button to create a new, blank character.</p>
  </div>

  <div id="character-details-container" data-bind="template: { 
      name: 'character-template',
      if: currentCharacter,
      data: currentCharacter,
      afterRender: setupTemplateUI }"></div>
</div>


<%= javascript_tag do -%>
  $(document).ready(function() {
    window.charactersListViewModel = new CharactersListViewModel([]);
    ko.applyBindings(window.charactersListViewModel);

    $("input#search-character").focus();

    $.getJSON("<%= url_for action: "index" %>")
      .done(function(data) {

        data.forEach(function(o) {
          var characterViewModel = new CharacterViewModel(o);
          window.charactersListViewModel.characters.push(characterViewModel);
        });
      });
  });
<% end -%>


<script type="text/html" id="character-template"></script>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>Characteristics:</strong>
  <%= @character.characteristics %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digitalbattlemat</title>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700|Merriweather:400,700|Lora:400,700|Oxygen:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", controller_name, "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.2.12/jquery.jgrowl.min.css" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.2.12/jquery.jgrowl.min.js"></script>
</head>
<body>
  <header>
    <div id="navigation-box">
      <span id="logo"><%= image_tag 'Logo.png' %></span>
      <nav>
        <ul>
          <li><a href="<%= url_for controller: :characters %>"><span class="navicon"><%= image_tag 'Icon-Characters.png' %></span>Characters</a></li>
          <li class="<%= params[:controller] == "mats" ? "active" : "" %>">
            <a href="<%= url_for controller: :mats %>">
              <span class="navicon"><%= image_tag 'Icon-Swords.png' %></span>
              Battle Screen
            </a>
          </li>
          <li><a href="#"><span class="navicon"><%= image_tag 'Icon-Maps.png' %></span>Maps</a></li>
        </ul>
      </nav>
    </div>
  </header>
  <main>
    <div id="content-box">
      <%= yield %>
    </div>
  </main>

</body>
</html>

app/views/layouts/plain.html.erb
<html>
	<head>
		<title>Digital Battle Mat</title>
		<%= stylesheet_link_tag 'fonts' %>
		<%= stylesheet_link_tag 'buttons' %>
		<%= stylesheet_link_tag 'dialogues' %>
		<%= stylesheet_link_tag 'mat_elements' %>
		<%= javascript_include_tag :defaults %>
	</head>
	<body>
		<!-- This is the shadow, which can be globally enabled or disabled -->
		<div id="shadow"></div>
		<%= yield %>
	</body>
</html>

app/views/mats/_form.html.erb
<%= form_for(@mat) do |f| %>
  <% if @mat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mat.errors.count, "error") %> prohibited this mat from being saved:</h2>

      <ul>
      <% @mat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mats/_index_mat_list_item.erb
<li id="mat-<%= mat.id %>" style="padding: 0.2em 0 0.2em 0">
    <p style="margin-bottom: 0.2em">
        <strong><%= mat.description %></strong>
    </p>
    <div class="button-mat-show">
        <%= link_to "Open", 
            :action => "edit", :id => mat.id %>
    </div>&nbsp;
    <div class="button-mat-delete">
      <%=
        link_to_remote("Delete", {
            :url => { :action => "destroy", :id => mat.id },
            :method => :delete
        })
      %>
    </div>
</li>

app/views/mats/_new_mat_form.erb
<li id="new-mat-form">
    <% form_remote_for :mat, :url => { :action => "create" } do |f| %>
        <%= f.text_area "description", { :rows => "3", :cols => "40" } %><br/>
        <div class="button-ok" onclick="this.parentNode.onsubmit();"></div>
    <% end %>
</li>

app/views/mats/edit.haml
=javascript_include_tag 'mat_edit_controls.js'
=javascript_include_tag 'mat.js'

%h1=@mat.description

#mat-mini-container

:javascript
  var miniMat = new BattleMat(#{@mat.id}, "mat-mini-container");
  miniMat.setAuthenticityToken("#{form_authenticity_token}").build();

app/views/mats/edit.html.erb
<h1>Editing mat</h1>

<%= render 'form' %>

<%= link_to 'Show', @mat %> |
<%= link_to 'Back', mats_path %>

app/views/mats/index.html.erb
<h1>Listing mats</h1>

<table>
  <thead>
    <tr>
      <th>Hash</th>
      <th>User</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mats.each do |mat| %>
      <tr>
        <td><%= mat.title %></td>
        <td><%= link_to 'Show', mat %></td>
        <td><%= link_to 'Edit', edit_mat_path(mat) %></td>
        <td><%= link_to 'Destroy', mat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= form_tag(action: "create") do %>
  <%= hidden_field(:mat, :title) %>
  <%= submit_tag 'New Mat' %>
<% end %>

<script type="application/javascript">
  $("input[type=submit]").button()
</script>

app/views/mats/new.html.erb
<h1>New mat</h1>

<%= render 'form' %>

<%= link_to 'Back', mats_path %>

app/views/mats/show.haml
#mat-container

app/views/mats/show.html.erb
<script id="card-template" type="text/html">
  <div class="charactercard character-card">
    <div class="character-name">
      <h1>
        <span data-bind="text: name" class="editable"></span><input type="text" data-bind="value: name" />
      </h1>
    </div>

    <div>
      <dl>
        <dt>Class</dt>
        <dd><span data-bind="text: className"></span></dd>
        <dt>Level</dt>
        <dd><span data-bind="text: level" class="editable"></span><input type="text" data-bind="value: level" size="2" /></dd>
        <dt>Life Points</dt>
        <dd><span data-bind="text: lifePoints"></span></dd>
        <dt>Initiative</dt>
        <dd class="character-initiative"><span data-bind="text: initiative"></span></dd>
      </dl>
    </div>

    <div class="characteristics-container">
      <h2>Characteristics</h2>
      <dl>
        <dt>STR</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.strength"></span>
          <input type="number" data-bind="value: characteristics.strength" size="2"/>
        </dd>
        <dt>CON</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.constitution"></span>
          <input type="number" data-bind="value: characteristics.constitution" size="2"/>
        </dd>
        <dt>DEX</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.dexterity"></span>
          <input type="number" data-bind="value: characteristics.dexterity" size="2"/>
        </dd>
        <dt>AGI</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.agility"></span>
          <input type="number" data-bind="value: characteristics.agility" size="2"/>
        </dd>
        <dt>INT</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.intelligence"></span>
          <input type="number" data-bind="value: characteristics.intelligence" size="2"/>
        </dd>
        <dt>POW</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.power"></span>
          <input type="number" data-bind="value: characteristics.power" size="2"/>
        </dd>
        <dt>WP</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.willpower"></span>
          <input type="number" data-bind="value: characteristics.willpower" size="2"/>
        </dd>
        <dt>PER</dt>
        <dd>
          <span class="editable" data-bind="text: characteristics.perception"></span>
          <input type="number" data-bind="value: characteristics.perception" size="2"/>
        </dd>
      </dl>
    </div>


    <div class="weapons-container">
      <h2>Weapons</h2>
      <label for="character-weapon">Use Weapon:</label> 
      <select name="character-weapon" class="action-set-weapon">
        <option value="unarmed">Unarmed</option>
      </select>
    </h2>


    <div class="character-actions">
      <button class="action-remove-character">Remove Character</button>
      <button class="action-edit-character" data-bind="click: edit">Edit Character</button>
      <button class="action-clone-character" data-bind="click: cloneCharacter">Clone Character</button>
      <button class="action-attack">Attack</button>
      <button class="action-cast-spell">Cast Spell</button>
    </div>
  </div>
</script>


<div id="actionbar">
  <div>
    <dl>
      <dt>Rounds:</dt>
      <dd><span data-bind="text: nRounds"></span></dd>
    </dl>
  </div>
  <div>
    <button id="actionRollInitiative" data-bind="click: rollInitiative, visible: isGameMaster">
      Roll Initiative
    </button>
    <button id="actionSetTrigger">Set Trigger</button>
    <button id="action-roll-dice">Roll Dices</button>
    <button id="actionInvite" data-bind="visible: isGameMaster">Invite Players</button>
  </div>
</div>


<div id="notice">
  <p><%= notice %></p>
</div>


<div id="mainarea">
  <div id="card-container" data-bind="template: { name: 'card-template', foreach:  characters, afterRender: addItems }">
    <div id="card-add" class="charactercard">
      <div><a href="#"><%= image_tag 'Icon-Plus-128x128.png' %><br/><span>Add Character</span></a></div>
    </div>
  </div>
</div>


<div id="dialog-roll-dice-template" title="Roll Dice" style="display: none;">
  <form>
    <label for="dice-roll-dicecode">
      Dice Code (e.g., 1d10 – <a href="http://www.rolz.org/">Help</a>):
    </label>
    <input type="text" name="dice-roll-dicecode"></input> <button>Roll!</button>
  </form>

  <p class="dialog-roll-dice-result-p" style="display: none;">
    <strong>Result:</strong> <span class="dialog-roll-dice-result"></span>
  </p>

  <form style="display: none;">
    <p class="dice-roll-set-trigger">
      <label for="dialog-roll-dice-trigger-title">Trigger Title:</label>
      <input type="text" name="dialog-roll-dice-trigger-title"/>
    </p>
  </form>
</div>


<div id="dialog-roll-error" title="Error during roll">
  <p>
    <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 50px 0;"></span>
    Your dice roll failed for a technical reason.
  </p>
  <p>Please try again.</p>
</div>


<%= javascript_tag do -%>
  $(document).ready(function() {
    setupMat();
  });
<% end -%>